default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: localhost
  username: postgres
  password: postgres
  database: tinkoff_rates_development

test:
  <<: *default
  host: localhost
  username: postgres
  password: postgres
  database: tinkoff_rates_test

production:
  <<: *default
  database: tinkoff_rates_production
  username: tinkoff_rates
  password: <%= ENV['TINKOFF_RATES_DATABASE_PASSWORD'] %>
